### ISSUE TITLE
Scroll position of the calendar widget should be 'fixed'

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#258]
The scroll position of the calendar widget changes whenever a user scrolls down and adds a slot to the calendar. Hopefully the gif is enough to illustrate the point:

![2020-04-26 00 45 23](https://user-images.githubusercontent.com/6923650/80292488-566b5280-8757-11ea-8094-935fd98afaf1.gif)

**Comment by Samson303** [comment]
Fixed

**Comment by MathisBullinger** [comment]
@Samson303 the fix is not to just not scroll the calendar. The calendar is scrolled to later in the day on purpose because otherwise, the evening won't be visible. If you want to avoid the jump, save the scroll position of the calendar and reapply it when the component is rerendered.

**Comment by malikpiara** [comment]
This is still not fixed @Samson303

**Comment by malikpiara** [comment]
Today I was using Upframe and I noticed this bug is still not fixed. This is a kind reminder to bring your attention to this :)

**Comment by MathisBullinger** [comment]
@Samson303 are you working on this, or should I take over the issue?

**Comment by Samson303** [comment]
I won't have time till at least 8 pm to work on that issue so you can take over. I think the fix that I had for it last time did not revert you back to 7 am when saved so I had the wrong fix.
